version: "3"
services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: city_hospital
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: