spring:
  application:
    name: city-hospital
  datasource:
    url: jdbc:postgresql://localhost:5432/city_hospital
    driverClassName: org.postgresql.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
